# hugo.toml for my Hugo Site

baseURL = 'https://blog.princetonstrong.online'
languageCode = 'en-us'
theme = "hugo-themes-nightfall"

[params.styles]
color = "orange"

[menu]
  [[menu.header]]
    name = "about"
    url = "/about"
    weight = 0


[params]
user = "$USER"
hostname = "online"
footerHtml = 'Â© 2025, CC-0, Princeton A. Strong.'
  [params.author]
    name = "Princeton A. Strong"  # Website and RSS feed author
    email = "princeton.strong@outlook.com"  # RSS feed email address

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "email"
url = "mailto:princeton.strong@outlook.com"
aria = "My e-Mail Address"

