# hugo.toml for my Hugo Site

baseURL = ''
languageCode = 'en-us'
theme = "hugo-themes-nightfall"

[params.styles]
color = "green"

[menu]
  [[menu.header]]
    name = "about"
    weight = 0
    url = "about"

[params]
user = "$USER"
hostname = "online"
footerHtml = 'Â© 2025 Princeton A. Strong. Licensed under the Apache License 2.0.'
  [params.author]
    name = "Princeton A. Strong"  # Website and RSS feed author
    email = "princeton.strong@outlook.com"  # RSS feed email address

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/borninthedark"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "email"
url = "mailto:princeton.strong@outlook.com"
aria = "My e-Mail Address"

